---
title: "Thesis - Data Cleaning"
author: "Rachael Pyram"
date: "2023-09-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading in data
```{r}
#importing data
import = read.csv("C:/Users/racha/Desktop/raw.csv")

#removing extraneous qualtrics variables
  ##note: raw var is the reference variable (preserves original dataset for troubleshooting)
raw = import[-c(1:3), -c(1:17)]

```

## Removing those who failed attention checks
```{r}
#importing list of rejected PID's
  ##note: all rejections failed the attention check
reject = read.csv("C:/Users/racha/Desktop/rejections.csv")

#creating merged dataset; merging on PID
data = merge(raw, reject, by = "PID", all.x = TRUE)

#in the "RejectionRationale" col, setting NAs to 10, so everyone who did not fail an attention check has a value of 10 (everyone who did fail has "Failed attention check")
data$RejectionRationale[is.na(data$RejectionRationale)] = 10

#filtering data var to only include people who passed the attention check (has val = 10 in "RejectionRationale" col)
library(dplyr)
data = data %>% filter(RejectionRationale == '10')

  ##note: 8 people failed the attention check, leaving a total n of 430
```

## Recoding the Measures
```{r}
#recode function (replaced text anchors with numbers)

recode_5pt =  function(x) {
  case_when(x %in% c("Strongly disagree") ~ 1,
            x %in% c("Somewhat disagree") ~ 2,
            x %in% c("Neither agree nor disagree") ~ 3,
            x %in% c("Somewhat agree") ~ 4,
            x %in% c("Strongly Agree") ~ 5)
}

#applying function to dataset
data = data %>% mutate_at(c(3:40, 45:47), recode_5pt)
data = data %>% mutate_at(c(3:40, 45:47), as.numeric) #forcing num for analysis
```

## Demographic Recoding
```{r}
#function to recode race/ethnicity question
race = function(x) {
  case_when(x %in% c("White") ~ 1,
            x %in% c("Black or African American") ~ 2,
            x %in% c("American Indian or Alaska Native") ~ 3,
            x %in% c("Native Hawaiian or Pacific Islander") ~ 4,
            x %in% c("Other") ~ 5,
            is.na(x) ~ 99, #ensures missing data doesn't get classified under "mixed race"
            .default = 6) #note: this constitutes all mixed race individuals
}

#applying function
data = data %>% mutate_at(c(49), race)


#function to recode gender question
gender = function(x) {
  case_when(x %in% c("Male") ~ 1,
            x %in% c("Female") ~ 2,
            x %in% c("Non-binary / third gender") ~ 3,
            x %in% c("Prefer not to say") ~ 4)
}

#applying function
data = data %>% mutate_at(c(48), gender)


#function to recode gender question
edu = function(x) {
  case_when(x %in% c("Less than high school") ~ 1,
            x %in% c("High school graduate") ~ 2,
            x %in% c("Some college") ~ 3,
            x %in% c("2 year degree") ~ 4,
            x %in% c("4 year degree") ~ 5,
            x %in% c("Professional degree (e.g., Master's, Doctorate, or other Professional degree)") ~ 6)
}

#applying function
data = data %>% mutate_at(c(52), edu)

```

## Exporting
```{r}
#exporting clean data
write.csv(data, file = "C:/Users/racha/Desktop/clean.csv")

```